config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :restaurants do
    resources :comments do
      put 'upvote', to: 'comments#upvote'
    end
  end
  root 'restaurants#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :restaurant
  validates :restaurant, presence: true
  has_ancestry

  def self.upvote(id)
    comment = find(id)
    comment.update_attributes(rank: comment.rank.to_i + 1)
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :comments
  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params.merge(restaurant_id: params[:restaurant_id]))
  end

  def upvote
    Comment.upvote(params[:comment_id])
    @comment = Comment.find(params[:comment_id])
    render :create
  end

  def comment_params
    params.required(:comment).permit(:body, :author, :parent_id)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end
  def show
    @restaurants = Restaurant.find(params[:id])
    @comments = @restaurants.comments
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "React Rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <style>
      ul { 
        list-style-type: none;
      }
      .row.collapse{
        margin-left: 20px;
      }
    </style>
  </head>

  <body>
    <nav class="top-bar foundation-bar" data-topbar>
      <section class="top-bar-left">
      <ul class="menu">
        <li class="name">
            <a href='/'>Reilly Restaurants</a>
        </li>
      </ul>
      </section>

      <section class="top-bar-right">
      <ul class="menu">
        <li>
          <%= link_to "manage restaurants", "/admin" %>
        </li>
      </ul>
      </section>
    </nav>
    <div class="row">
      <div class="large-12 columns">
          <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/restaurants/index.html.erb
<h2>Restaurants</h2>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant, restaurant_path(restaurant) %></li>
  <% end %>
</ul>

app/views/restaurants/show.html.erb
<div class="row">
  <h3><%= @restaurants.name %></h3>
</div>
<div class="row">
  <div class="columns medium-6">
    <p>
      <%= @restaurants.description %>
    </p>
  </div>
    <div class="columns medium-6">
      <h4>Comments</h4>
      <%= react_component('CommentSection', restaurantId: @restaurants.id, comments: raw(render(template: 'comments/index.json.jbuilder'))) %>
    </div>
</div>